/**
 * `ade claude-teams` — launch Claude Code with its experimental agent-teams
 * feature pointed at ADE's tmux shim, so teammates materialize as real ADE
 * panes.
 *
 * Everything here follows the Phase-0 probe (PROBE-CONTRACT.md), which found
 * two things that make the feature look dead when it is not:
 *
 * - The env var ALONE yields in-process teammates: `DEFAULT_TEAMMATE_MODE` is
 *   `in-process`, so `--teammate-mode tmux` must be passed.
 * - A non-interactive session short-circuits to in-process before any backend
 *   selection, so a real PTY is required. We warn rather than refuse.
 *
 * The feature is gated server-side (`tengu_amber_flint`) and can be switched
 * off remotely without a version change, which is why the command stays
 * marked EXPERIMENTAL in --help.
 */
import { type SpawnSyncReturns, spawnSync } from "node:child_process";
import { chmodSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { delimiter, join } from "node:path";
import type { Command, LocalIo } from "../command";
import { EXIT } from "../errors";
import { singleQuote } from "../tmux-compat/quote";
import {
	CompatStore,
	defaultStoreDir,
	emptyStore,
	type StoreData,
} from "../tmux-compat/store";

export const SHIM_DIRNAME = "claude-teams-bin";
/** What the shim reports itself as; also the pane id the leader is bound to. */
export const LEADER_PANE_ID = "%0";
export const FAKE_TMUX_ENV = "/fake-socket,0,0";

/**
 * How the shim re-enters this CLI. In a dev checkout `ade` is a bun shim, so
 * the reliable invocation is "the interpreter running me, plus the script it
 * was given" rather than the name `ade`, which may not be on PATH at all.
 */
export function resolveInvocation(
	env: NodeJS.ProcessEnv,
	execPath: string,
	scriptPath: string | undefined,
): string {
	const override = env.ADE_CLI_INVOCATION;
	if (override) return override;
	if (scriptPath) return `${singleQuote(execPath)} ${singleQuote(scriptPath)}`;
	return "ade";
}

export function shimScript(invocation: string): string {
	return [
		"#!/bin/sh",
		"# Generated by `ade claude-teams`. Do not edit — rewritten on every launch.",
		"# Claude Code's agent-teams backend runs this believing it is tmux;",
		"# ade tmux-compat translates the argv into ADE control-plane calls.",
		`exec ${invocation} tmux-compat "$@"`,
		"",
	].join("\n");
}

/** Writes ~/.ade/claude-teams-bin/tmux, idempotently. Returns the directory. */
export function materializeShim(adeDir: string, invocation: string): string {
	const dir = join(adeDir, SHIM_DIRNAME);
	mkdirSync(dir, { recursive: true });
	const path = join(dir, "tmux");
	const content = shimScript(invocation);
	let current: string | null = null;
	try {
		current = readFileSync(path, "utf8");
	} catch {
		current = null;
	}
	if (current !== content) writeFileSync(path, content, { mode: 0o755 });
	chmodSync(path, 0o755);
	return dir;
}

export interface LaunchPlan {
	command: string;
	args: string[];
	env: NodeJS.ProcessEnv;
}

export const LAUNCHES_DIRNAME = "claude-teams";

/**
 * The mapping store this launch owns.
 *
 * Deliberately NOT the default store dir. `seedStore` resets the store and
 * rebinds `%0` to the launching pane, so two `ade claude-teams` running at
 * once over one shared file meant the second launch wiped the first's
 * mappings and repointed its leader pane — every subsequent teammate spawn
 * from the first session then landed in the wrong ADE pane. A per-launch
 * directory gives each session its own file.
 *
 * An inherited `ADE_TMUX_COMPAT_DIR` wins: that is an explicit choice by
 * whoever set it, and the tests use it.
 */
export function launchStoreDir(
	adeDir: string,
	env: NodeJS.ProcessEnv,
	pid: number,
	now: number,
): string {
	return (
		env.ADE_TMUX_COMPAT_DIR ?? join(adeDir, LAUNCHES_DIRNAME, `${pid}-${now}`)
	);
}

export function buildLaunch(
	userArgs: string[],
	env: NodeJS.ProcessEnv,
	shimDir: string,
	compatDir: string,
): LaunchPlan {
	const args = [...userArgs];
	// Passing it twice would make Claude's own arg parser pick one at random;
	// an explicit user choice wins.
	if (!args.includes("--teammate-mode")) args.push("--teammate-mode", "tmux");

	return {
		command: env.ADE_CLAUDE_BIN ?? "claude",
		args,
		env: {
			...env,
			PATH: `${shimDir}${delimiter}${env.PATH ?? ""}`,
			TMUX: FAKE_TMUX_ENV,
			TMUX_PANE: LEADER_PANE_ID,
			CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS: "1",
			// The shim is `exec ade tmux-compat "$@"`, so every shim invocation
			// inherits this and `defaultStoreDir` reads it back. A bare
			// `ade tmux-compat` outside a launch still gets the default dir.
			ADE_TMUX_COMPAT_DIR: compatDir,
		},
	};
}

/**
 * Resets the mapping store and binds `%0` to the pane this command runs in.
 *
 * A reset, not a merge: every mapping from a previous launch points at panes
 * that may no longer exist, and a stale `%1` would send a teammate's command
 * into whatever pane inherited that ADE id.
 */
export async function seedStore(
	store: CompatStore,
	env: NodeJS.ProcessEnv,
): Promise<void> {
	await store.transact((data: StoreData) => {
		const fresh = emptyStore();
		Object.assign(data, fresh);
		data.sessions.$0 = { id: "$0", name: "ade", windowOrder: ["@0"] };
		data.windows["@0"] = {
			id: "@0",
			sessionId: "$0",
			name: "ade",
			adeTabId: null,
			options: {},
			paneOrder: [LEADER_PANE_ID],
		};
		data.panes[LEADER_PANE_ID] = {
			id: LEADER_PANE_ID,
			windowId: "@0",
			adePaneId: env.ADE_SURFACE_ID ?? null,
			title: null,
			options: {},
			state: "shell",
			command: null,
		};
		data.counters = { pane: 1, window: 1, session: 1 };
	});
}

export interface TeamsOverrides {
	env?: NodeJS.ProcessEnv;
	platform?: NodeJS.Platform;
	adeDir?: string;
	execPath?: string;
	scriptPath?: string;
	isTty?: boolean;
	/** Overrides the per-launch store dir; the tests pin it to a tmpdir. */
	compatDir?: string;
	store?: CompatStore;
	spawn?: (plan: LaunchPlan) => SpawnSyncReturns<Buffer>;
}

export async function runClaudeTeams(
	argv: string[],
	io: LocalIo,
	overrides: TeamsOverrides = {},
): Promise<number> {
	const env = overrides.env ?? process.env;
	const platform = overrides.platform ?? process.platform;

	if (platform === "win32") {
		io.stderr("ade claude-teams: macOS only in v1");
		return EXIT.USAGE;
	}

	const adeDir = overrides.adeDir ?? defaultStoreDir(env);
	const invocation = resolveInvocation(
		env,
		overrides.execPath ?? process.execPath,
		overrides.scriptPath ?? process.argv[1],
	);
	const shimDir = materializeShim(adeDir, invocation);

	const compatDir =
		overrides.compatDir ?? launchStoreDir(adeDir, env, process.pid, Date.now());
	await seedStore(overrides.store ?? new CompatStore(compatDir), env);

	const isTty = overrides.isTty ?? Boolean(process.stdout.isTTY);
	if (!isTty) {
		io.stderr(
			"warning: stdout is not a TTY — Claude Code forces in-process teammates " +
				"on non-interactive sessions, so no ADE panes will be created.",
		);
	}

	const plan = buildLaunch(argv, env, shimDir, compatDir);
	const spawn =
		overrides.spawn ??
		((p: LaunchPlan) =>
			spawnSync(p.command, p.args, { stdio: "inherit", env: p.env }));

	const result = spawn(plan);
	if (result.error) {
		const err = result.error as NodeJS.ErrnoException;
		io.stderr(
			err.code === "ENOENT"
				? `ade claude-teams: could not run "${plan.command}" (not on PATH)`
				: `ade claude-teams: ${err.message}`,
		);
		return EXIT.USAGE;
	}
	if (typeof result.status === "number") return result.status;
	if (result.signal) {
		io.stderr(`ade claude-teams: claude terminated by ${result.signal}`);
		return EXIT.SERVER_ERROR;
	}
	return EXIT.OK;
}

export const teamsCommands: Command[] = [
	{
		name: "claude-teams",
		group: "Teams",
		summary:
			"EXPERIMENTAL: launch Claude Code with agent teams as real ADE panes",
		kind: "local",
		rawArgs: true,
		notes:
			"Usage: ade claude-teams [--continue] [--model <name>] [claude args…]\n" +
			"Every argument is passed through to `claude` verbatim.\n\n" +
			"EXPERIMENTAL. Agent teams is an undocumented Claude Code feature behind\n" +
			"a SERVER-SIDE kill switch, so a teammate spawn may simply never arrive\n" +
			"even when this command works. macOS only in v1 (win32 exits 2).\n\n" +
			"What it does:\n" +
			"  1. Writes ~/.ade/claude-teams-bin/tmux — a shim that execs\n" +
			"     `ade tmux-compat`.\n" +
			"  2. Runs claude with that directory first on PATH, TMUX/TMUX_PANE set,\n" +
			"     CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1, and --teammate-mode tmux\n" +
			"     appended (the env var ALONE still gives in-process teammates).\n\n" +
			"Needs a real terminal: Claude Code forces in-process teammates when\n" +
			"stdout is not a TTY, and this command warns rather than refusing.",
		runLocal: (argv, io) => runClaudeTeams(argv, io),
	},
];
