import {
	copyFileSync,
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { getAgentHome } from "./agent-home";

/**
 * Duplicate an agent's PERSONA into another agent (issue #41,
 * create-from-existing). Persona vs. memory is decided by WHERE the agent
 * wrote something, never by parsing content at copy time:
 *
 *   Copied  — memory/AGENT.md (re-stamped for the new identity),
 *             memory/USER.md, skills/** (every file, recursively).
 *   NOT copied — memory/MEMORY.md, memory/memories/*, .writeback-protocol.md
 *             and runtime bridge files (all regenerated by the normal
 *             scaffold). Exception: the source MEMORY.md's "## Lessons"
 *             section is carried over iff `includeLessons` is set.
 *
 * Ordering contract: run AFTER scaffoldAgentMemory. The scaffold's
 * writeIfEmpty never overwrites a non-empty file, so this module uses PLAIN
 * writes to overwrite the freshly-templated AGENT.md / USER.md / skills seed
 * with the source persona. The source agent is never written to.
 *
 * Re-stamping is plain string substitution of the source agent's identity
 * (name, id, home path) with the target's — both are known, so no semantic
 * parsing is needed or attempted.
 *
 * Import-time DB-free (node:fs + path helpers only) so it stays unit-testable
 * under bun on Windows, where better-sqlite3 cannot load.
 */

export interface AgentIdentity {
	agentId: string;
	agentName: string;
	/** Defaults to the derived <APP_DATA>/agents/<id> home. */
	agentHome?: string;
}

export interface DuplicatePersonaParams {
	source: AgentIdentity;
	target: AgentIdentity;
	/** Also carry the source MEMORY.md's "## Lessons" section over. */
	includeLessons?: boolean;
}

export interface DuplicatePersonaResult {
	/** Paths (relative to the target agent home) that were written. */
	copied: string[];
	/** True iff a Lessons section was found in the source and carried over. */
	lessonsCarried: boolean;
}

function escapeRegExp(s: string): string {
	return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Re-stamp source-agent identity embedded in persona text with the target's.
 * Longest-first, most-specific-first: home paths (native and forward-slash
 * forms) before the raw id, the id before the name. The name is replaced only
 * at word boundaries so a short name never mangles unrelated words.
 */
export function restampPersonaContent(
	content: string,
	source: Required<AgentIdentity>,
	target: Required<AgentIdentity>,
): string {
	let out = content;
	const literalPairs: Array<[string, string]> = [
		[source.agentHome, target.agentHome],
		[
			source.agentHome.replaceAll("\\", "/"),
			target.agentHome.replaceAll("\\", "/"),
		],
		[source.agentId, target.agentId],
	];
	for (const [from, to] of literalPairs) {
		if (from && from !== to) out = out.split(from).join(to);
	}
	if (source.agentName && source.agentName !== target.agentName) {
		out = out.replace(
			new RegExp(
				`(?<![A-Za-z0-9_])${escapeRegExp(source.agentName)}(?![A-Za-z0-9_])`,
				"g",
			),
			() => target.agentName,
		);
	}
	return out;
}

/**
 * Extract the body of MEMORY.md's "## Lessons" section (content between the
 * heading and the next "## " heading or EOF), without the heading itself.
 * Returns null when the section is absent.
 */
export function extractLessonsSection(memoryMd: string): string | null {
	const lines = memoryMd.split("\n");
	const start = lines.findIndex((l) => /^##\s+Lessons\s*$/.test(l));
	if (start === -1) return null;
	let end = lines.length;
	for (let i = start + 1; i < lines.length; i++) {
		if (/^##\s/.test(lines[i])) {
			end = i;
			break;
		}
	}
	return lines.slice(start + 1, end).join("\n");
}

/**
 * Replace the body of the "## Lessons" section in `memoryMd` with
 * `lessonsBody`. Appends a new section at the end when none exists.
 */
export function replaceLessonsSection(
	memoryMd: string,
	lessonsBody: string,
): string {
	const lines = memoryMd.split("\n");
	const start = lines.findIndex((l) => /^##\s+Lessons\s*$/.test(l));
	const body = lessonsBody.replace(/\s+$/, "");
	if (start === -1) {
		return `${memoryMd.replace(/\s+$/, "")}\n\n## Lessons\n${body}\n`;
	}
	let end = lines.length;
	for (let i = start + 1; i < lines.length; i++) {
		if (/^##\s/.test(lines[i])) {
			end = i;
			break;
		}
	}
	const replacement = body === "" ? [] : body.split("\n");
	// Keep a blank separator before a following section.
	if (end < lines.length) replacement.push("");
	lines.splice(start + 1, end - (start + 1), ...replacement);
	return lines.join("\n");
}

/** Recursively list files under `dir` as paths relative to it. */
function listFilesRecursive(dir: string, prefix = ""): string[] {
	const out: string[] = [];
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const name = String(entry.name);
		const rel = prefix ? `${prefix}/${name}` : name;
		if (entry.isDirectory()) {
			out.push(...listFilesRecursive(join(dir, name), rel));
		} else if (entry.isFile()) {
			out.push(rel);
		}
	}
	return out;
}

/**
 * Copy the source agent's persona over the target's fresh scaffold.
 * Missing source files are skipped (an agent created before the memory
 * scaffold may lack some) — the target keeps its scaffold template for those.
 */
export function duplicateAgentPersona({
	source,
	target,
	includeLessons = false,
}: DuplicatePersonaParams): DuplicatePersonaResult {
	const src: Required<AgentIdentity> = {
		...source,
		agentHome: source.agentHome ?? getAgentHome(source.agentId),
	};
	const tgt: Required<AgentIdentity> = {
		...target,
		agentHome: target.agentHome ?? getAgentHome(target.agentId),
	};
	const restamp = (content: string) =>
		restampPersonaContent(content, src, tgt);

	// getAgentMemoryDir(id) === join(getAgentHome(id), "memory"); with the
	// home already resolved (or overridden) the join is the same for both.
	const sourceMemoryDir = join(src.agentHome, "memory");
	const targetMemoryDir = join(tgt.agentHome, "memory");

	const copied: string[] = [];

	// Persona memory files: AGENT.md (re-stamped identity/paths), USER.md.
	// Plain writes — deliberately overwrite the scaffold's fresh templates.
	mkdirSync(targetMemoryDir, { recursive: true });
	for (const name of ["AGENT.md", "USER.md"]) {
		const srcPath = join(sourceMemoryDir, name);
		if (!existsSync(srcPath)) continue;
		writeFileSync(
			join(targetMemoryDir, name),
			restamp(readFileSync(srcPath, "utf8")),
			"utf8",
		);
		copied.push(`memory/${name}`);
	}

	// Skills: reusable procedures — copy the whole tree, overwriting the
	// scaffold's seed files. Markdown is re-stamped (skill bodies may
	// reference the agent's home paths); other files copy byte-for-byte.
	const sourceSkillsDir = join(src.agentHome, "skills");
	const targetSkillsDir = join(tgt.agentHome, "skills");
	if (existsSync(sourceSkillsDir)) {
		for (const rel of listFilesRecursive(sourceSkillsDir)) {
			const from = join(sourceSkillsDir, rel);
			const to = join(targetSkillsDir, rel);
			mkdirSync(dirname(to), { recursive: true });
			if (rel.endsWith(".md")) {
				writeFileSync(to, restamp(readFileSync(from, "utf8")), "utf8");
			} else {
				copyFileSync(from, to);
			}
			copied.push(`skills/${rel}`);
		}
	}

	// Optional gray-zone carry-over: just the "## Lessons" section, into the
	// target's fresh MEMORY.md. Everything else in MEMORY.md stays fresh.
	let lessonsCarried = false;
	if (includeLessons) {
		const srcMemoryPath = join(sourceMemoryDir, "MEMORY.md");
		const tgtMemoryPath = join(targetMemoryDir, "MEMORY.md");
		if (existsSync(srcMemoryPath) && existsSync(tgtMemoryPath)) {
			const lessons = extractLessonsSection(
				readFileSync(srcMemoryPath, "utf8"),
			);
			if (lessons !== null && lessons.trim().length > 0) {
				writeFileSync(
					tgtMemoryPath,
					replaceLessonsSection(
						readFileSync(tgtMemoryPath, "utf8"),
						restamp(lessons),
					),
					"utf8",
				);
				copied.push("memory/MEMORY.md (Lessons section)");
				lessonsCarried = true;
			}
		}
	}

	return { copied, lessonsCarried };
}
